import { Providers } from "@/redux/provider";
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f5ebe9]">
        <div>
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}